#!/bin/sh

# Task 1 : This line was commented

# Task 2 : ECHO
echo "This is my Day 1 task"

# Task 3 : Variables
name="khaleel"
n="1"
number="2"

# Task 4 : Using Variables
greetings="$name, $n, $number!"
echo "$greetings test is done!"

# Task  5: Using Built-in Variables
# Get the current user
current_user="$USER"

# Get the current date and time
current_date_time="$(date)"

# Get the system's hostname
system_hostname="$HOSTNAME"

echo "Current User: $current_user"
echo "Current Date and Time: $current_date_time"
echo "System Hostname: $system_hostname"

# Task 6 : Wildcards
echo "below we are showing the .kk files list"
ls *.kk *.txt

echo "Thank you!"
